version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ozon
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ozonTest
