version: '3'
services:
  ozontest:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT
      - STORAGE_TYPE
      - POSTGRES_LINK
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ozonTest
    ports:
      - '5432:5432'